[build]
  publish = "dist"
  command = "npm run generate"
[build.environment]
  NODE_VERSION = "11"
  
[[redirects]]
  from = "/.well-known/assetlinks.json"
  to = "https://boringcuriosity.github.io/pwa/assetlinks.json"
  status = 200
  force = true
